# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test and Linting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v2

    - name: Create env file
      run: |
        touch .env
        echo DEV_ACCESS_TOKEN_SECRET=${{ secrets.DEV_ACCESS_TOKEN_SECRET }} >> .env
        echo DEV_REFRESH_TOKEN_SECRET=${{ secrets.DEV_REFRESH_TOKEN_SECRET }} >> .env
        echo DEV_GH_API_CLIENT_ID=${{ secrets.DEV_GH_API_CLIENT_ID }} >> .env
        echo DEV_GH_API_SECRET=${{ secrets.DEV_GH_API_SECRET }} >> .env
        echo DEV_GH_SHA_SECRET=${{ secrets.DEV_GH_SHA_SECRET }} >> .env
        echo DEV_AES_SECRET=${{ secrets.DEV_AES_SECRET }} >> .env
        echo DEV_NGROK_AUTH_TOKEN=${{ secrets.DEV_NGROK_AUTH_TOKEN }} >> .env

    - name: Run test and lint
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run test
    - run: npm run lint

  frontend:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: frontend

    steps:
    - uses: actions/checkout@v2

    - name: Run test and lint
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm test -- --watchAll=false --passWithNoTests
    - run: npm run lint
