# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Unit Test and Linting Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend:

    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: backend
    
    steps:
    - uses: actions/checkout@v2

    - name: Create env file
      run: |
        touch .env
        echo ACCESS_TOKEN_SECRET=${{ secrets.ACCESS_TOKEN_SECRET }} >> .env
        echo REFRESH_TOKEN_SECRET=${{ secrets.REFRESH_TOKEN_SECRET }} >> .env
        echo .env

    - name: Run test and lint
      uses: actions/setup-node@v2
      with:
        node-version: 15.x
    - run: npm ci
    - run: npm run test
    - run: npm run lint
